### ISSUE TITLE
v0.4 and dev pip installation broken

### ISSUE THREAD

**Issue by bpartridge** [bcarlin/flask-scss#16]
```
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/vx/6hg82skd71d_f8_mk97gp72h0000gn/T/pip-build-FOo3AV/Flask-Scss/setup.py", line 38, in <module>
        data_files=make_data_files('doc/.build/html', 'doc') + [
      File "/private/var/folders/vx/6hg82skd71d_f8_mk97gp72h0000gn/T/pip-build-FOo3AV/Flask-Scss/setup.py", line 14, in make_data_files
        for elem in os.listdir(root_path):
    OSError: [Errno 2] No such file or directory: 'doc/.build/html'

```

In setup.py, you do an os.listdir on this directory, but it doesn't exist in the repository; it must be .gitignored on your local machine.

Please test pip installs from github in a virtualenv before pushing to pip in the future!

**Comment by bcarlin** [comment]
It is fixed in a new 0.5 version. 

I'm sorry for this screw-up
